# This file was generated by GoReleaser. DO NOT EDIT.
cask "runtimepulse" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "703442d4be92a158c0cddef7024769716244d860b04c241bc6d525ed3a2f7677"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6596c431f543ac36c8e2a53587160acb24e35d767007028a4fbcd026b1c4881d"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc133fc74cbc96b6082b8b2d4a7469506cf0a88b47999c4892b462842d87d807"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44fa3c1a331ff4edd5e0a7197c1cef122478d65b1fa45a39a6ed841c1f1e9976"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_linux_arm64.tar.gz"
    end
  end

  name "runtimepulse"
  desc "Event-driven session continuation engine for AI coding agents"
  homepage "https://github.com/tufantunc/RuntimePulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runtimepulse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runtimepulse"]
    end
  end

  # No zap stanza required

end
