# This file was generated by GoReleaser. DO NOT EDIT.
cask "runtimepulse" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "e021d691f57e7681b987acc592c1bfd62895e5b5803842b137f0ebe020f18982"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8babba66ddd4d84b91f95e83cf4a9d55c0ffdabdeff654fd0095211a0b6d57d"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c934abadf513302c66e6344013307c02d82b39999c22155007aca4770b009dde"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ff906fa31ca319808358f516ce3ce5f6370dea2a0463942e7526cfedf293d9f"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_linux_arm64.tar.gz"
    end
  end

  name "runtimepulse"
  desc "Event-driven session continuation engine for AI coding agents"
  homepage "https://github.com/tufantunc/RuntimePulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runtimepulse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runtimepulse"]
    end
  end

  # No zap stanza required

end
