# This file was generated by GoReleaser. DO NOT EDIT.
cask "runtimepulse" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "603460fbaad557414cb0c5b1cfd2ab69759e92951faf2ca1d6d729c2abaf096b"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "402ace052fcf7f0f70d39bfb15628d4ef4a2213d54fd3a1f98cea648d82f739b"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4bac85f68a2576ccc090a282a454f1376ff48fe008bed58bfb267f5d4311a5e"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5d538eff158ab0130eecac1566fc81e70150af45e02bb4a1f429eaaf3a0229d"
      url "https://github.com/tufantunc/RuntimePulse/releases/download/v#{version}/runtimepulse_linux_arm64.tar.gz"
    end
  end

  name "runtimepulse"
  desc "Event-driven session continuation engine for AI coding agents"
  homepage "https://github.com/tufantunc/RuntimePulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runtimepulse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runtimepulse"]
    end
  end

  # No zap stanza required

end
